# Generated by Django 5.2.3 on 2025-07-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="is_published",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
