# Generated by Django 5.2.3 on 2025-07-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_recipe_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="recipes/cover/%Y/%m/%d"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
